title: PyTorchFI Docs
description: PyTorchFI documentation
baseurl: "/"
url: "https://pytorchfi.github.io"

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
  ]

search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "PyTorchFI on GitHub":
    - "//github.com/pytorchfi/"

color_scheme: nil

ga_tracking: UA-139336911-1
